apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-custom-g6i5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/burrsitis-tenant/partner-catalog-custom/partner-catalog-custom-g6i5@sha256:ca7f1d715ffefb6855d9f078ac7cac006349e6f63aa5f39c4a19122f0c087c62
        name: my-java-springboot
        resources: {}
status: {}
